# Generated by Django 4.0 on 2022-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsApp_message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wa_id', models.IntegerField()),
                ('msg_type', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('msg_id', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
