# Generated by Django 3.2.13 on 2022-05-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsapp_message',
            old_name='wa_id',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='whatsapp_message',
            old_name='msg_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='whatsapp_message',
            name='created',
        ),
        migrations.RemoveField(
            model_name='whatsapp_message',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='whatsapp_message',
            name='read',
        ),
        migrations.RemoveField(
            model_name='whatsapp_message',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='whatsapp_message',
            name='updated',
        ),
    ]
